name: checks
on:
  push:
    paths-ignore:
      - LICENSE
      - README.md
      - CONTRIBUTING.md
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: shellcheck
        uses: sudo-bot/action-shellcheck@latest
        with:
          cli-args: "setup"
